spring.application.name=tomato

#spring.ai.openai.api-key=OWN_API_KEY
#
#spring.ai.openai.chat.model=gpt-4o-mini
#


tomato.system-prompt=classpath:system-prompt.txt
spring.ai.model.chat=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:3b